@extends('layouts.app')
@section('title', 'Expenses')
@section('content')
<div class="page-header"><div><h1>Expenses</h1><p>Review, filter and manage recorded spending.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addExpenseModal"><i class="bi bi-plus-lg me-1"></i>Add Expense</button></div>
<div class="card filter-card mb-4"><div class="card-body"><form class="row g-3 align-items-end demo-filter"><div class="col-lg-5"><label class="form-label">Search</label><input class="form-control" placeholder="Search description"></div><div class="col-sm-6 col-lg-3"><label class="form-label">Category</label><select class="form-select"><option>All categories</option>@foreach($categories as $category)<option>{{ $category->name }}</option>@endforeach</select></div><div class="col-sm-6 col-lg-2"><label class="form-label">Month</label><input class="form-control" type="month" value="2026-07"></div><div class="col-lg-2 d-grid"><button class="btn btn-primary"><i class="bi bi-funnel me-1"></i>Filter</button></div></form></div></div>
<div class="card"><div class="card-body"><div class="section-heading"><div><h5 class="card-title">Expense Records</h5><p class="card-subtitle">{{ $expenses->count() }} expenses · Total ₹{{ number_format($expenses->sum('amount'), 2) }}</p></div></div><div class="table-responsive"><table class="table align-middle"><thead><tr><th>Date</th><th>Category</th><th>Description</th><th>Amount</th><th class="text-end">Action</th></tr></thead><tbody>
@foreach($expenses as $expense)<tr><td>{{ $expense->expense_date->format('d M Y') }}</td><td><span class="category-badge">{{ $expense->category->name }}</span></td><td>{{ $expense->description }}</td><td class="fw-semibold">₹{{ number_format($expense->amount, 2) }}</td><td><div class="table-actions"><button class="btn btn-light btn-sm" data-bs-toggle="modal" data-bs-target="#editExpense{{ $expense->id }}"><i class="bi bi-pencil"></i></button><button class="btn btn-light btn-sm text-danger demo-action"><i class="bi bi-trash"></i></button></div></td></tr>@endforeach
</tbody></table></div></div></div>
@endsection
@push('modals')
<div class="modal fade" id="addExpenseModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form class="demo-form"><div class="modal-header"><div><h5 class="modal-title">Add Expense</h5><small class="text-muted">Record a new transaction.</small></div><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">@include('expenses.form-modal', ['expense' => null])</div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Save Expense</button></div></form></div></div></div>
@foreach($expenses as $expense)<div class="modal fade" id="editExpense{{ $expense->id }}" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form class="demo-form"><div class="modal-header"><h5 class="modal-title">Edit Expense</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">@include('expenses.form-modal', ['expense' => $expense])</div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Update Expense</button></div></form></div></div></div>@endforeach
@endpush
