@extends('layouts.app')
@section('title', 'Categories')
@section('content')
<div class="page-header"><div><h1>Expense Categories</h1><p>Organize spending into clear, reusable groups.</p></div><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#addCategoryModal"><i class="bi bi-plus-lg me-1"></i>Add Category</button></div>
<div class="card"><div class="card-body"><div class="section-heading"><div><h5 class="card-title">Category Records</h5><p class="card-subtitle">{{ $categories->count() }} categories available</p></div><input id="categorySearch" type="search" class="form-control table-search" placeholder="Search categories"></div><div class="table-responsive"><table class="table align-middle" id="categoryTable"><thead><tr><th>Name</th><th>Expenses</th><th>Status</th><th class="text-end">Action</th></tr></thead><tbody>
@foreach($categories as $category)<tr><td><span class="category-name"><i class="bi bi-tag"></i><strong>{{ $category->name }}</strong></span></td><td>{{ $category->expenses_count }}</td><td><span class="status-badge {{ $category->is_active ? 'success' : 'muted' }}">{{ $category->is_active ? 'Active' : 'Inactive' }}</span></td><td><div class="table-actions"><button class="btn btn-light btn-sm" data-bs-toggle="modal" data-bs-target="#editCategory{{ $category->id }}"><i class="bi bi-pencil"></i></button><button class="btn btn-light btn-sm text-danger demo-action"><i class="bi bi-trash"></i></button></div></td></tr>@endforeach
</tbody></table></div></div></div>
@endsection
@push('modals')
<div class="modal fade" id="addCategoryModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form class="demo-form"><div class="modal-header"><h5 class="modal-title">Add Category</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Category Name</label><input class="form-control mb-3" required><div class="form-check form-switch"><input class="form-check-input" type="checkbox" checked><label class="form-check-label">Active</label></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Save Category</button></div></form></div></div></div>
@foreach($categories as $category)<div class="modal fade" id="editCategory{{ $category->id }}" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><form class="demo-form"><div class="modal-header"><h5 class="modal-title">Edit Category</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><label class="form-label">Category Name</label><input class="form-control mb-3" value="{{ $category->name }}" required><div class="form-check form-switch"><input class="form-check-input" type="checkbox" @checked($category->is_active)><label class="form-check-label">Active</label></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">Cancel</button><button class="btn btn-primary">Update Category</button></div></form></div></div></div>@endforeach
@endpush
